@startuml

namespace doci {
    abstract class CI {
        __ protected members __
            # size_t N
            # size_t K
            # size_t nbf
            # doci::State lowest_eigenstate
            # doci::CI_basis* basis
            # doci::Hamiltonian* hamiltonian
        __ protected methods __
            # virtual void **calculateCI**(size_t start, size_t end)=0
	        # virtual void **construct**()=0
        == constructors ==
	        **CI**()
	        **CI**(CI_basis *ciBasis)
	    __ public methods __
	        + Hamiltonian* **getHamiltonian**() const
    }


    class DOCI {
        __ private members __
            - size_t npairs
            - bmqc::AddressingScheme ad_mat
        __ private methods __
            - void **calculateCI**(size_t start, size_t end) override
            - void **construct**() override
        == constructors ==
            **DOCI**(CI_basis *ciBasis)
    }


    class State {
        __ private members __
            - double eigenvalue
            - Eigen::VectorXd eigenvector
        == constructors ==
            **State**()
            **State**(double eigenvalue, Eigen::VectorXd eigenvector)
        __ public methods __
            + double **get_eigenvalue**()
            + const Eigen::VectorXd& **get_eigenvector**() const

            + bool **operator<**(const doci::State& rhs)
            + bool **operator>**(const doci::State& rhs)
            + bool **operator==**(const doci::State& rhs)
    }


    class CI_basis {
        __ private members __
            - Eigen::MatrixXd one_ints
            - Eigen::Tensor<double, 4> two_ints
            - double internuclear_repulsion
            - size_t K
            - size_t N
        == constructors ==
            **CI_basis**()
            **CI_basis**(hf::rhf::RHF& rhf)
            **CI_basis**(const std::string& filename)
        __ public methods __
            + void **rotate**(double rot, size_t index1, size_t index2)
            + double **get_one_int**(size_t index1, size_t index2) const
            + double **get_two_int**(size_t index1, size_t index2, size_t index3, size_t index4) const
            + double **get_internuclear_repulsion**() const
            + size_t **get_K**() const
            + size_t **get_N**() const
    }


    abstract class Hamiltonian {
        __ protected members __
            # size_t nbf
            # Eigen::VectorXd eigenvalues
            # Eigen::MatrixXd eigenvectors
            # std::vector<doci::State> groundstates= { doci::State (std::numeric_limits<double>::max(), Eigen::VectorXd()) }
        __ protected methods __
            # void **groundStates**(doci::State state)
        __ public methods __
            + const std::vector<doci::State>& **get_groundstates**() const
            + virtual void **add**(double value, size_t index1, size_t index2)=0
            + virtual void **solve**()=0
            + {static} Hamiltonian* **make_hamiltonian**(size_t nbf);
    }


    class DenseHamiltonian {
        __ private members __
            - Eigen::MatrixXd hamiltonian
        == constructors ==
            **DenseHamiltonian**(size_t nbf)
        __ public methods __
            + const Eigen::MatrixXd& **get_hamiltonian**() const

            + void **solve**() override
            + void **add**(double value, size_t index1, size_t index2) override
    }
}


namespace bmqc {
    class AddressingScheme {
        == constructors ==
            AddressingScheme(size_t K, size_t N)
        __ public methods __
            + const Matrixi& get_vertex_weights() const
            + size_t fetchAddress(const boost::dynamic_bitset<> bitVector)
            + boost::dynamic_bitset<> **generateBitVector_bitset**(size_t address)
    }

    class global {
        .. bitset ..
            void next_bitset_permutation(boost::dynamic_bitset<>& v)
    }


}

namespace libwint {
    class SOBasis {
        == constructors ==
            **SOBasis**(const libwint::AOBasis& ao_basis, Eigen::MatrixXd& C)
        __ public methods __
            + inline const libwint::AOBasis& **get_ao_basis**() const
            + inline Eigen::MatrixXd& **get_h_SO**() const
            + inline Eigen::Tensor<double, 4>& **get_g_SO**() const
            + inline const size_t **get_K**() const

            + void **transform**(Eigen::MatrixXd& T)
            + void **transformJacobi**(size_t p, size_t q, double angle)
    }
}

namespace hf {
    namespace rhf {
        class RHF {
            __ public data __
                + libwint::Basis &basis
        }
    }
}


doci.Hamiltonian o--> doci.State

doci.DenseHamiltonian --|> doci.Hamiltonian

doci.CI *--> doci.State
doci.CI o--> libwint.SOBasis
doci.CI *--> doci.Hamiltonian

doci.DOCI --|> doci.CI
doci.DOCI *--> bmqc.AddressingScheme
doci.DOCI ..> bmqc.global


@enduml